export const UPDATE_UPCOMING_LAUNCHES = 'UPDATE_UPCOMING_LAUNCHES'
export const UPDATE_PAST_LAUNCHES = 'UPDATE_PAST_LAUNCHES'
export const SORT_UPCOMING_LAUNCHES = 'SORT_UPCOMING_LAUNCHES'
export const SORT_PAST_LAUNCHES = 'SORT_PAST_LAUNCHES'
